name: CI Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - prod
      - uat
      - dev
      - feature/**

jobs:
  lint:
    name: Run Golang CI-Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run Golang CI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.3
          args: "--config .golangci.yml --timeout 5m ./src/"

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run Go Tests
        run: |
          go test ./... -v
